Imp: last commit

diff --git a/all/lib/copies-for-libs/drya-lib-1--for--drya-lib-4 b/all/lib/copies-for-libs/drya-lib-1--for--drya-lib-4
--- a/all/lib/copies-for-libs/drya-lib-1--for--drya-lib-4
+++ b/all/lib/copies-for-libs/drya-lib-1--for--drya-lib-4
@@ -12,14 +12,14 @@
 #
 #
 #     # Sourcing DRYa Lib 1: Color schemes
-#        v_lib1=${v_REPOS_CENTER}/DRYa/all/lib/drya-lib-1-colors-greets.sh
+#        V_lib1=${v_REPOS_CENTER}/DRYa/all/lib/drya-lib-1-colors-greets.sh
 #        [[ -f $v_lib1 ]] && source $v_lib1 || read -s -n 1 -p "DRYa: drya-lib-1 does not exist (error)"
 #
-#        # Examples: F_greet, F_greet2, F_talk, F_done, f_anyK, f_Hline, f_horizlina, f_verticline, etc... [From the repo at: "https://github.com/SeivaDArve/DRYa.git"]
+#        # Examples: F_greet, F_greet2, F_talk, F_done, F_anyK, F_Hline, F_horizlina, F_verticline, etc... [From the repo at: "https://github.com/SeivaDArve/DRYa.git"]
 #           V_greet="DRYa"
 #           V_talk="DRYa: "
-#           v_txt="<text-used-at-f_anyK-fx>"
-#           v_hzl (uDev: variable that decides what is the char that is written in the horizontal line)
+#           V_txt="<text-used-at-f_anyK-fx>"
+#           V_hzl (uDev: variable that decides what is the char that is written in the horizontal line)
 #  
 #
 
@@ -33,96 +33,96 @@
 # uDev: create fx to increment a var: i=(($i + 1))
 # uDev: add fx for `date` command
 # uDev: with ANSI, move cursor up one line
-# uDev: f_clear_current_line, (Apagar texto da linha atual ate ao fundo com ANSI)
-#       f_count_var_size,     (saber quantas letrar tem `echo ${#variavel}`)
-#       f_create_tmp_file     (dar um nome e saber que esse ficheiro tmp foi criado)
+# uDev: F_clear_current_line, (Apagar texto da linha atual ate ao fundo com ANSI)
+#       F_count_var_size,     (saber quantas letrar tem `echo ${#variavel}`)
+#       F_create_tmp_file     (dar um nome e saber que esse ficheiro tmp foi criado)
 
 
 
 
-function f_test_dependencie_tput {
+function F_test_dependencie_tput {
    # Testar a existencia de ncurses-utils
 
    #echo "uDev"
 
-   v_status=1
-   v_status=0
+   V_status=1
+   V_status=0
 }
 
 
-function f_c1 {	
+function F_c1 {	
    # Fx for color 1
    # This function is to be used when something is SEARCHED
 
-   f_test_dependencie_tput
+   F_test_dependencie_tput
    [[ $v_status == 0 ]] && tput setaf 5 
 }
 
-function f_c2 { 
+function F_c2 { 
    # Fx for color 2
 
-   f_test_dependencie_tput
+   F_test_dependencie_tput
    [[ $v_status == 0 ]] && tput setaf 12
 }
 
-function f_c3 { 
+function F_c3 { 
    # Fx for color 3
 
    # Mentioning user input or valiable input
    # This function is to be used when something is DECLAIRED
 
-   f_test_dependencie_tput
+   F_test_dependencie_tput
    [[ $v_status == 0 ]] && tput setaf 3
 }
 
-function f_c4 { 
+function F_c4 { 
    # Fx for color 4
 
    # Similar to Bold. Used in: F_talk
    # This function is to be used when something is ASKED
-   f_test_dependencie_tput
+   F_test_dependencie_tput
    [[ $v_status == 0 ]] && tput setaf 4
 }
 
-function f_c5 { 
+function F_c5 { 
    # Fx for color 5
 
    # Similar to Bold
-   f_test_dependencie_tput
+   F_test_dependencie_tput
    [[ $v_status == 0 ]] && tput setaf 6
 }
 
-function f_c6 { 
+function F_c6 { 
    # Fx for color 6
 
    # Used for ASCII Drya Logo, centered to the screen
-   f_test_dependencie_tput
+   F_test_dependencie_tput
    [[ $v_status == 0 ]] && tput setaf 28
    [[ $v_status == 0 ]] && tput bold
 }
 
-function f_c7 {
+function F_c7 {
    # Fx for ANSI green color
 
    GREEN='\033[0;32m'
    echo -en "$GREEN"
 }
 
-function f_c8 {
+function F_c8 {
    # Fx for ANSI red color
 
    RED='\033[0;31m'
    echo -en "$RED"
 }
 
-function f_rc { 
+function F_rc { 
    # Fx for color reset
 
    # This function is to be used when styles are to be CLEARED
    [[ $v_status == 0 ]] && tput sgr0
 }
 
-function f_colors_without_tput {
+function F_colors_without_tput {
    # Text Colors before discovering '$ tput setaf'
       RESTORE=$(echo -en '\001\033[0m\002')
           RED=$(echo -en '\001\033[00;31m\002')
@@ -131,13 +131,13 @@ function f_colors_without_tput {
    # > `echo ${RED}To do something, specify an argument like \"G 2\"${RESTORE}`
 }  
 
-function f_cON {
+function F_cON {
    # Fx for make cursor visible
 
    [[ $v_status == 0 ]] && tput cnorm
 }
 
-function f_cOFF {
+function F_cOFF {
    # Fx for make cursor invisible
 
    [[ $v_status == 0 ]] && tput civis
@@ -149,20 +149,20 @@ function F_greet {
 
    # uDev: Confirmar se no futuro pode haver problemas com a font: Enviar para omni-log
 
-   # If previously the variable $V_greet was not set by any script, then assign a <Placeholder> to it.
-      [[ -z $V_greet ]] && V_greet="< V_greet >"
+   # If previously the variable $v_greet was not set by any script, then assign a <Placeholder> to it.
+      [[ -z $v_greet ]] && V_greet="< V_greet >"
 
    # Creting an alternative message in case figlet is not installed
-      v_basename=$(basename $0)
-      v_2nd_option="<< $V_greet >>\n\n > Running: $v_basename\n > Missing: \`figlet\` \n"
+      V_basename=$(basename $0)
+      V_2nd_option="<< $v_greet >>\n\n > Running: $v_basename\n > Missing: \`figlet\` \n"
 
    clear
-   f_c2
-   figlet $V_greet 2>/dev/null || echo -e "$v_2nd_option"
-   f_rc
+   F_c2
+   figlet $v_greet 2>/dev/null || echo -e "$v_2nd_option"
+   F_rc
 }
 
-function f_Greet {
+function F_Greet {
    # Same as F_greet, but for Text that uses all the ascii space like "g" in "Yoga". This fx only adds another empty line below the ascii "g"
    F_greet
    echo
@@ -175,63 +175,63 @@ function F_greet2 {
       || echo -e "DRYa: app available \n > (For a pretty logo, install figlet)"  # In case figlet or tput are not installed, echo only "DRYa" instead
 }
 
-# uDev: F_greet, f_Greet, F_greet2 ... change to f_g1, f_g2, f_g3 ...
+# uDev: F_greet, F_Greet, F_greet2 ... change to F_g1, F_g2, F_g3 ...
 
 function F_talk {
-   # uDev: change to f_tk
+   # uDev: change to F_tk
    # Colorfull text to preceed any text of any important text line
 
-   # If previously no script gave the variable $V_talk, then, assign "DRYa-lib-1" to it
-      [[ -z $V_talk ]] && V_talk="< V_talk > "
+   # If previously no script gave the variable $v_talk, then, assign "DRYa-lib-1" to it
+      [[ -z $v_talk ]] && V_talk="< V_talk > "
 
-   f_c2; echo -n "$V_talk"
-   f_rc
+   F_c2; echo -n "$v_talk"
+   F_rc
 }
 
-function f_suc1 {
+function F_suc1 {
    # Fx number 1 of 2 
    # Use this to give confirmation the previous command has successfull
-   # Use it after f_anyK fx
+   # Use it after F_anyK fx
 
    # EXAMPLE: 
    #     echo "Did this message work?" && echo "Success!"
-   #     echo "Did this message work?" && f_suc1 || f_suc2
-   #     echo "Did this message work?" && f_suc1 || f_suc2 && exit 1
+   #     echo "Did this message work?" && F_suc1 || F_suc2
+   #     echo "Did this message work?" && F_suc1 || F_suc2 && exit 1
 
            echo -n " > "
-     f_c7; echo       "Success!"
-     f_rc
+     F_c7; echo       "Success!"
+     F_rc
 
    # Set a variable to indicate exit status
-      v_suc=0
+      V_suc=0
 }
 
-function f_suc2 {
+function F_suc2 {
    # Fx number 2 of 2 
    # Use this to give confirmation the previous command has successfull
-   # Use it after f_anyK fx
+   # Use it after F_anyK fx
 
    # EXAMPLE: 
    #     echo "Did this message work?" && echo "Success!"
-   #     echo "Did this message work?" && f_suc1 || f_suc2
-   #     echo "Did this message work?" && f_suc1 || f_suc2 && exit 1
+   #     echo "Did this message work?" && F_suc1 || F_suc2
+   #     echo "Did this message work?" && F_suc1 || F_suc2 && exit 1
 
            echo -n " > "
-     f_c8; echo       "Failed!"
-     f_rc
+     F_c8; echo       "Failed!"
+     F_rc
 
    # Set a variable to indicate exit status
-      v_suc=1
+      V_suc=1
 }
 
 function F_done {
    # Use this after all precesses are finished
 
    F_talk; echo "Done!"
-   f_rc
+   F_rc
 }
 
-function f_anyK {
+function F_anyK {
    # Press Any key to continue
    # Or wait X seconds
 
@@ -241,8 +241,8 @@ function f_anyK {
    # A variavel $v_txt tem de ser definida antes desta fx ser chamada
       # EXEMPLO:
       #
-      # v_txt="Editado X"
-      # f_anyK
+      # V_txt="Editado X"
+      # F_anyK
       #
       # EFEITO: 
       # DRYa: Are you sure: "Editar X"
@@ -251,29 +251,29 @@ function f_anyK {
 
 
    # Set how many seconds to wait before automatically continue
-      v_secs=5
+      V_secs=5
 
    # Message
-      v_msg=" ... (Continue: ANY KEY | Cancel: Ctrl-C ) "
+      V_msg=" ... (Continue: ANY KEY | Cancel: Ctrl-C ) "
 
    # Set $v_txt to " ... " in case the user forgets to set it (must be unset before this fx finishes
-      [[ -z $v_txt ]] && v_txt=" ... "
+      [[ -z $v_txt ]] && V_txt=" ... "
 
    # Text to print
          #echo
    F_talk; echo -n 'Are you sure? `'
-     f_c5; echo -n "$v_txt"   # A variavel $v_txt tem de ser definida antes desta fx ser chamada
-     f_rc; echo '`'
+     F_c5; echo -n "$v_txt"   # A variavel $v_txt tem de ser definida antes desta fx ser chamada
+     F_rc; echo '`'
            echo -n "$v_msg"
            read -sn1
-     f_rc; echo -e "\r\033[K > A Continuar..."
+     F_rc; echo -e "\r\033[K > A Continuar..."
 
    # Removing variables before the fx finished
-      unset v_txt
+      unset V_txt
 }
 
 
-function f_prsD {
+function F_prsD {
    # Press key 'D' or 'd' to continue
    # Or wait X seconds
 
@@ -283,8 +283,8 @@ function f_prsD {
    # A variavel $v_txt tem de ser definida antes desta fx ser chamada
       # EXEMPLO:
       #
-      # v_txt="Editado X"
-      # f_prsD
+      # V_txt="Editado X"
+      # F_prsD
       #
       # EFEITO: 
       # DRYa: Are you sure: "Editar X"
@@ -293,45 +293,45 @@ function f_prsD {
 
 
    # Set how many seconds to wait before automatically continue
-      v_secs=5
+      V_secs=5
 
    # Message
-      v_msg=" ... (Continue: 'd' or 'D' | Cancel: Ctrl-C or Any Key) "
+      V_msg=" ... (Continue: 'd' or 'D' | Cancel: Ctrl-C or Any Key) "
 
    # Set $v_txt to " ... " in case the user forgets to set it (must be unset before this fx finishes
-      [[ -z $v_txt ]] && v_txt=" ... "
+      [[ -z $v_txt ]] && V_txt=" ... "
 
    # Text to print
          #echo
    F_talk; echo -n 'Are you sure? `'
-     f_c5; echo -n "$v_txt"   # A variavel $v_txt tem de ser definida antes desta fx ser chamada
-     f_rc; echo '`'
+     F_c5; echo -n "$v_txt"   # A variavel $v_txt tem de ser definida antes desta fx ser chamada
+     F_rc; echo '`'
            echo -n "$v_msg"
-           read -sn1 v_ans
+           read -sn1 V_ans
            echo
      
      [[ -n $v_ans ]] && echo -e "\r\033[K > A Continuar..."
 
    # Removing variables before the fx finished
-      unset v_txt
+      unset V_txt
 }
 
-function f_hzl {
+function F_hzl {
    # Prints an horizontal line according to the amount to line existent in the current terminal
    # This fx exists also at .../init-bin/horizontal-line.sh
 
    # If the script that used this library does not set the variable that fills the line, then the character is set as default here
-      [[ -z $v_hzl ]] && v_hzl="-"
+      [[ -z $v_hzl ]] && V_hzl="-"
       
-   v_cols=$(tput cols)
+   V_cols=$(tput cols)
    printf "%*s" $v_cols | tr " " "$v_hzl"
 }
 
-function f_horizline {
+function F_horizline {
    # Criar uma linha horizontal do tamanho correto do ecra
 
    # Buscar tamanho correto (precisa da dependencia `tput`)
-      v_cols=$(tput cols)
+      V_cols=$(tput cols)
 
    # Escrever uma linha no ecra
       for i in $(seq $v_cols); do
@@ -341,20 +341,20 @@ function f_horizline {
 
 
 
-function f_verticline {
+function F_verticline {
 	v_lines=$(tput lines)
 	for i in $(seq $v_lines); do
    	echo -ne "   |\n" 
 	done
 }
 
-#  function f_nr_test {
+#  function F_nr_test {
 #     # Testa se a Var fornecida é numero ou nao
-#     # v_nr
+#     # V_nr
 #     
 #     case $v_nr in
 #        1 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0)
-#           v_nr=true
+#           V_nr=true
 #           ;;
 #     esac
 #  }
@@ -366,10 +366,10 @@ function db {
    echo
 }
 
-function f_debug {
+function F_debug {
    # Creating a pause in the middle of the script for debugging process
    
-   # Var to print as debug message: v_debug (do not set this var if not needed)
+   # Var to print as debug message: V_debug (do not set this var if not needed)
    echo "Debuging... $v_debug"
    echo -n " > 3"
    read -sn1
@@ -379,21 +379,21 @@ function f_debug {
    read -sn1
 }
 
-function f_pin {
+function F_pin {
    # Adicionar pin aos pedidos de certas fx
-   # v_pin is defined at source-all-drya-files
-   # v_pin=$(grep "v_pin" ${v_REPOS_CENTER}/DRYa/all/source-all-drya-file)
-   v_pin=0000
+   # V_pin is defined at source-all-drya-files
+   # V_pin=$(grep "v_pin" ${v_REPOS_CENTER}/DRYa/all/source-all-drya-file)
+   V_pin=0000
 
    # Se no 'main' script o user definiu texto para apresentar no ecra, entao esse texto é apresentado
       [[ -n $v_pin_txt ]] && echo "$v_pin_txt" 
 
-   read -sp " > Introduz um PIN: " v_ans
+   read -sp " > Introduz um PIN: " V_ans
 
-   [[ $v_ans != $v_pin ]] && f_suc2 && exit 1
-   [[ $v_ans == $v_pin ]] && f_suc1
+   [[ $v_ans != $v_pin ]] && F_suc2 && exit 1
+   [[ $v_ans == $v_pin ]] && F_suc1
 
-   unset v_pin_txt
+   unset V_pin_txt
 
 }
 
@@ -403,16 +403,16 @@ function f_pin {
 #
 #  # For the lines: 
 #     # Count number of lines in the terminal:
-#        v_tLines=$(stty size | cut -d ' ' -f 1)
+#        V_tLines=$(stty size | cut -d ' ' -f 1)
 #          #echo "current number of lines in the terminal is: $v_tLines"
 #
 #     # Dividing that number into 2
-#        v_half_tLines=$(expr $v_tLines / 2)
+#        V_half_tLines=$(expr $v_tLines / 2)
 #         #echo "Half of that is (rounded number): $v_half_tLines"
 #
 #     # And the into 2
-#        v_half_half_tLines=$(expr $v_half_tLines / 2)
-#        v_lines=$v_half_half_tLines
+#        V_half_half_tLines=$(expr $v_half_tLines / 2)
+#        V_lines=$v_half_half_tLines
 #
 #
 #
@@ -420,17 +420,17 @@ function f_pin {
 #
 #  # For the Columns: 
 #     # Count number of lines in the terminal:
-#        v_tCols=$COLUMNS
+#        V_tCols=$COLUMNS
 #          #echo "current number of columns in the terminal is: $v_tCols"
 #
 #     # Removing the number of characters from the text variables:
-#        v_tCols=$(expr $v_tCols - $v_char) 
+#        V_tCols=$(expr $v_tCols - $v_char) 
 #
 #     # Dividing that number into 2
-#        v_half_tCols=$(expr $v_tCols / 2)
+#        V_half_tCols=$(expr $v_tCols / 2)
 #        #echo "Half of that is (rounded number): $v_half_tCols"
 #
-#     v_cols=$v_half_tCols
+#     V_cols=$v_half_tCols
 #
 #
 #
