Working of select-loop-menu

diff --git a/install.uninstall/linux-or-WSL/master-bashrc/select-loop-menu b/install.uninstall/linux-or-WSL/master-bashrc/select-loop-menu
--- a/install.uninstall/linux-or-WSL/master-bashrc/select-loop-menu
+++ b/install.uninstall/linux-or-WSL/master-bashrc/select-loop-menu
@@ -11,6 +11,10 @@ function f_greet {
    figlet DRYa # -f standard.flf 2>/dev/null
 }
 
+function f_title {
+   echo -e " ( Initial Menu )\n"
+} 
+
 function f_1st {
    # This function belongs to the First Question
    echo -e "                 (Step 1 of 4)                 \n"
@@ -28,40 +32,61 @@ function f_2nd {
 
 function f_3rd {
    # This function belongs to the Third Question
-   echo -e " (Step 3 of 4) - Run script only side-by-side?\n"
+   echo -e "                 (Step 3 of 4)                 \n"
+   echo -e "       --- Checklist for instalation --- "
+   echo -e " [X] Do you have any dedicated dir for  repositories?"
+   echo -e " [X] Move DRYa repository into that place (or git clone it)"
+   echo -e " [ ] Running this script only side-by-side?\n"
 } 
 
 function f_4th {
    # This function belongs to the Forth Question
-   echo -e " (Step 4 of 4) - Everything seems ok. Shall we start the magic?\n"
+   echo -e "                 (Step 4 of 4)                 \n"
+   echo -e "       --- Checklist for instalation --- "
+   echo -e " [X] Do you have any dedicated dir for  repositories?"
+   echo -e " [X] Move DRYa repository into that place (or git clone it)"
+   echo -e " [X] Running this script only side-by-side?"
+   echo -e "  -  Everything seems ok tostart modifications"
+   echo -e " [ ] Shall we stat the magic?\n"
 } 
+
+function f_break_select_loops {
+   # This function f_break_select_loops evals if v_break_select_loops variable
+      # Is defined as either yes or no
+      # And returns a value to the user
+   
+   # If the variable is empty, do nothing, if "no", do nothing, if "yes" then break
+   if [[ -z $v_break_select_loops ]]; then echo -n ""
+      elif [[ $v_break_select_loops == "no" ]]; then echo -n ""
+      elif [[ $v_break_select_loops == "yes" ]]; 
+         then 
+            _break="break"
+            clear
+   fi
+}
 
 function f_1st_select {
    # Initial Statements (prompting the questions):
 	   # First Question:
          clear; f_greet; f_1st
 
-         select i in "(yes) to continue" "(no) to abort" "(help) to explain" "(back)" "exit"
+         select i in "(yes) to continue" "(no) to abort" "" "(help) to explain" "(back to Menu)" "exit"
          do
             case $i in
                "(yes) to continue")
-                  read -p " First question answered YES [ENTER]"
-                  f_2nd_select
+                  f_2nd_select;
+                  # Last, allow to script to flow by breaking all 'select loops'
+                     f_break_select_loops; eval $_break
+
                ;;
                "(no) to abort")
-                  echo " First question answered NO"
-                  echo
-                  echo " > For a correct instalation, you must be at the correct place (aborting)"
+                  echo " For a correct instalation, you should create a directory where all other"
+                  echo " Repositories go... (aborting)"
 
-                  # The back command cannot be used while sourcing, otherwise the entire terminal shuts down
-                    # If the answer given by the user was NO, then we will allow all the remaining
-                    # functions of this file to be loaded and we will also create a function
-                    # Discard them in the end. To do that, we will store in a variable our 
-                    # decicion of keeping the functions or discard the in the end in a variable
+                  # The exit command cannot be used while sourcing, otherwise the entire terminal shuts down
 
                     load_remaining_functions="no"
                     #export v_unload ## Aparently scripts cannot export variables while being sorced
-                    #back 1  
                     exit 1
                ;;
                "(help) to explain") 
@@ -79,13 +104,11 @@ function f_1st_select {
                     read -s -n 1
                     clear; f_greet ; f_1st
                ;;
-               "(back)")
+               "(back to Menu)")
                   clear; f_greet; f_title; break
                ;;
                "exit") echo "Bye"; exit 0 ;;
-               *)
-                  echo " > When running this script, please select either Yes or No (aborting)"
-               ;;
+               *) echo " That option is invalid. Press ENTER to clear screen"; read; clear; f_greet; f_1st ;;
               esac
          done
 }
@@ -94,16 +117,21 @@ function f_2nd_select {
    # Second question:
       clear; f_greet; f_2nd
 
-      select i in "(yes) to continue" "(no) to abort" "(help) to explain" "(back)"
+      select i in "(yes) to continue" "(no) to abort" "" "(help) to explain" "(back to Q1)"
       do
          case $i in 
             "(yes) to continue")
 
-               f_3rd_select
+               f_3rd_select;
+
+               # Last, allow to script to flow by breaking all 'select loops'
+                  f_break_select_loops; eval $_break
+
 
           ;;
           "(no) to abort")
             echo " Second question answered NO"
+                    exit 1
           ;;
           h) 
             echo " Asked for help at Second question"
@@ -115,9 +143,10 @@ function f_2nd_select {
                echo "   and that copy (this copy) should be moved into the directory you choose to be the holder of all repos"
                echo
          ;;
-         "(back)")
+         "(back to Q1)")
             clear; f_greet; f_1st; break
          ;;
+         *) echo " That option is invalid. Press ENTER to clear screen"; read; clear; f_greet; f_2nd ;;
         esac
       done
 
@@ -127,16 +156,21 @@ function f_3rd_select {
    # Third question:
       clear; f_greet; f_3rd
 
-      select i in "(yes) to continue" "(no) to abort" "(help) to explain" "(back)"
+      select i in "(yes) to continue" "(no) to abort" "" "(help) to explain" "(back to Q2)"
       do 
         case $i in 
           "(yes) to continue")
             echo " Third question answered YES"
 
             f_4rd_select
+
+            # Last, allow to script to flow by breaking all 'select loops'
+               f_break_select_loops; eval $_break
+
           ;;
           "(no) to abort")
             echo " Third question answered NO"
+                    exit 1
           ;;
           "(help) to explain") 
             clear; f_greet
@@ -154,34 +188,35 @@ function f_3rd_select {
                echo "be sourcing or running this script from anywhere"
                echo "and that would not work)"
           ;;
-          "(back)") clear; f_greet; f_2nd; break
+          "(back to Q2)") clear; f_greet; f_2nd; break
           ;;
-          *) echo " That option is invalid. Press ENTER 2x"; read; clear; f_greet; f_4th ;;
+          *) echo " That option is invalid. Press ENTER to clear screen"; read; clear; f_greet; f_3rd ;;
          esac
       done
 }
+
 
 function f_4rd_select {
    # Fourth question:
       clear; f_greet; f_4th
 
-      select i in "(yes) to continue" "(no) to abort" "(help) to explain" "(back)"
+      select i in "(yes) to continue" "(no) to abort" "" "(help) to explain" "(back to Q3)"
       do
          case $i in 
             "(yes) to continue")
-               echo " Forth question answered YES"
-               read
-               read
-               read
-               read
+               echo " All questions answered... Continuing the script"
                read
 
+               # After the 'select' loop breaks, it should carry this variable to indicate the next function
+                  # That the process of reaching this line of code was sucessfull or not
+                  # If the user used the script until this line, it means that the user wants to continue the installation
+                  # This variable enables the remaining of the instalation 
+                     load_remaining_functions="yes"
 
-               # Last, allow to script to flow
-                  echo " All questions answered... Continuing the script"
-                  echo "The remaining of this file will be sourced;)"
-                  load_remaining_functions="yes"
-                  #export v_unload ## Aparently scripts cannot export variables while being sourced
+                     #export v_unload ## Aparently scripts cannot export variables while being sourced
+
+               # Last, allow to script to flow by breaking all 'select loops'
+                  v_break_select_loops="yes"; f_break_select_loops; eval $_break
             ;;
            "(no) to abort")
              echo " Not ready to see magic... I see..."
@@ -194,8 +229,8 @@ function f_4rd_select {
              # Explanation
                echo " Magic is the instalation of such usefull software"
            ;;
-          "(back)") clear; f_greet; f_3rd; break ;;
-          *) echo " That option is invalid. Press ENTER 2x"; read; clear; f_greet; f_4th ;;
+          "(back to Q3)") clear; f_greet; f_3rd; break ;;
+          *) echo " That option is invalid. Press ENTER to clear screen"; read; clear; f_greet; f_4th ;;
          esac
       done
 }
@@ -208,18 +243,21 @@ function f_uninstall_1st {
 
 
 function f_menu {
-   # What do you want to do?
-
-   function f_title {
-      echo -e " ( Initial Menu )\n"
-   } 
+   # The first menu of the Installer/Uninstaller
 
    clear; f_greet; f_title
    PS3=" ----- Menu ---- > "
    select i in "drya install" "drya uninstall" "" "CLEAR SCREEN" options "exit"
       do
          case $i in
-            "drya install") echo "installing..."; f_1st_select ;;
+            "drya install") 
+
+               # Start the first of a few questions in a row
+                  f_1st_select 
+
+               # If the answers were all answered, allow to script to flow by breaking all 'select loops'
+                  f_break_select_loops; eval $_break
+            ;;
             "drya uninstall") echo "uninstalling"; f_uninstall_1st; break;;
             options) echo "options not ready yet"; read; clear; f_greet; f_title;;
             exit) echo "Bye"; break ;;
@@ -233,5 +271,8 @@ function f_menu {
             *) clear; f_greet; f_title ;;
          esac
       done
+
+echo "Last line of script"
+   
 }
 f_menu
